language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: GAd8nAafX44rSgEY2gDCCEsMutKPpDQnpUpwNUKMRc5YxW9PSwQbYeVOYBLeFWG5DmPUcszclJ+QRQwdyKvW8gfnmLdhade0JECPlepzNfZq+yF1FibgntQ3stRevs/T9hQA5YipqJs5Jt1Ej9UQ9lpJDnzduHT86kRxrXvyz0mbuSjucoGXxHP8wsUUe2TGhApt0nn0UB82HceyVXX3q+D6NeMLolCkV5HBLUd9UfScVBR0SGmUARcyRQUlSNFB8mei1CZaI0N4iB8i46IPIbv5h9wS3rkxlK1anazCmLBO3bb8lIEgoyTgpZszCScywMtQVoqxOyaglvG9wi9rfB+JRkJZM2WlSIkg5ncPJcF0a1nQyNtQZIRhQhm6xKwVlSt2klk6jgx646DUMKF3nJTPrn4BBMDR/rQ2g2IqzyjhnAkYhxOaxtDNp0EiH7mooZtGqrdV68EIg5qVcBwtSinXVbBnqeBFgM99Mcyi2vf4OrfmrCmRosla+LABCt8zzqUfW0jHwkszOjJwu11bfUQ1Sv+p+VsckFMrWfmpY1LT1U++UApgtDz75trjTckBbzhq8L0dRBfXoeLbhQyjGrHowEnmq8xvGVL7aYlTrvan8OjGfNTz7kdrNFc/8z7tzy85BevNmtXI7rxl12yTpHf86UHq3RARk8QKX2OrhsE=
  app: chats-and-robs
